<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cleaning_bot">
    <!-- Xacro property for color brightness and alpha. -->
    <xacro:property name="bright" value=".75" />
    <xacro:property name="alpha" value="1" />

    <!-- Xacro property for scale. -->
    <xacro:property name="scale" value=".15" />

    <!-- Scale derived from 'scale' property. -->
    <xacro:property name="chassis_radius" value="${scale*2}" />
    <xacro:property name="chassis_length" value="${scale*1}" />
    <xacro:property name="wheel_radius" value="${chassis_radius/2}" />
    <xacro:property name="wheel_length" value="${chassis_length/2}" />
    <xacro:property name="caster_radius" value="${chassis_radius/4}" />
    <xacro:property name="lidar_length" value="${chassis_radius/4}" />

    <xacro:property name="wheel_distance" value="${chassis_radius+wheel_length/2}" />

    <!-- Default inertial from ROS tutorials. -->
    <xacro:macro name="default_inertial" params="mass">
    <inertial>
        <mass value="${mass*scale}" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
    </xacro:macro>

    <!-- List of materials for easier viewing. -->
    <material name="red">
        <color rgba="${bright} 0.0 0.0 ${alpha}"/>
    </material>

    <material name="blue">
        <color rgba="0 0 ${bright} ${alpha}" />
    </material>

    <material name="green">
        <color rgba="0 ${bright} 0 ${alpha}" />
    </material>

    <material name="white">
        <color rgba="${bright} ${bright} ${bright} ${alpha}"/>    
    </material>

    <material name="purple">
        <color rgba="${bright} 0 ${bright*0.75} ${alpha}" />
    </material>

    <!-- This is the base link of the robot. A simple cylinderical chassis. -->
    <link name="base_link">
        <visual>
           <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_length}"/> 
           </geometry>
           <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_length}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="10" />
    </link>

    <!-- This is the left wheel link. -->
    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="10" />
    </link>

    <!-- This is the right wheel link. -->
    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="10" />
    </link>

    <!-- The caster wheel. -->
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="10" />
    </link>

    <!-- This is the lidar camera link mounted on top of the chassis. -->
    <link name="lidar_link">
        <visual>
            <geometry>
                <box size="${lidar_length} ${lidar_length} ${lidar_length}"/>
            </geometry>
            <material name="purple"/>
        </visual>
        <collision>
            <geometry>
                <box size="${lidar_length} ${lidar_length} ${lidar_length}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="1" />
    </link>

    <!-- This joint defines base/left-wheel joint. -->
    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 ${wheel_distance} -${chassis_length/2}" rpy="1.57 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <!-- This joint defines base/right-wheel joint. -->
    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 -${wheel_distance} -${chassis_length/2}" rpy="1.57 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <!-- This joint defines base/caster-wheel joint. -->
    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="0 0 -${chassis_length}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- This joint defines base/lidar joint. -->
    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="${chassis_radius-lidar_length/2} 0 ${chassis_length-lidar_length/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <gazebo>
        <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>
    </gazebo>

    <!-- Gazebo LiDAR sensor. -->
    <gazebo reference="lidar_link">
        <sensor name="lidar_sensor" type="gpu_lidar">
            <pose>0 0 0 0 0 0</pose>
            <update_rate>10</update_rate>

            <lidar>
            <scan>
                <horizontal>
                <samples>720</samples>
                <resolution>1</resolution>
                <min_angle>-1.5708</min_angle>
                <max_angle>1.5708</max_angle>
                </horizontal>
            </scan>

            <range>
                <min>0.1</min>
                <max>30.0</max>
                <resolution>0.01</resolution>
            </range>
            </lidar>

            <always_on>true</always_on>
            <visualize>true</visualize>

            <topic>/scan</topic>
        </sensor>
    </gazebo>

    <!-- Gazebo plugin for diff-drive. Allows the robot to move. -->
    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <!-- Wheel joints -->
            <left_joint>base_left_wheel_joint</left_joint>
            <right_joint>base_right_wheel_joint</right_joint>

            <!-- Robot kinematics -->
            <wheel_separation>${wheel_distance*2}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>

            <!-- Motion limits -->
            <max_linear_velocity>1.0</max_linear_velocity>
            <max_angular_velocity>2.0</max_angular_velocity>

            <!-- Command & odometry -->
            <topic>/cmd_vel</topic>
            <odom_topic>/odom</odom_topic>
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>

            <!-- Behavior -->
            <update_rate>50</update_rate>
            <publish_odom>true</publish_odom>
            <publish_tf>true</publish_tf>
        </plugin>
    </gazebo>
</robot>
